spring.application.name=stream-analytics-service
server.port=8086

spring.kafka.bootstrap-servers=localhost:9092

spring.cloud.function.definition=bookingCreatedStream;bookingConfirmedStream;bookingFailedStream

spring.cloud.stream.bindings.bookingCreatedStream-in-0.destination=booking-created
spring.cloud.stream.bindings.bookingConfirmedStream-in-0.destination=booking-confirmed
spring.cloud.stream.bindings.bookingFailedStream-in-0.destination=booking-failed

spring.cloud.stream.kafka.streams.binder.brokers=localhost:9092

spring.cloud.stream.kafka.streams.bindings.bookingCreatedStream-in-0.consumer.applicationId=stream-analytics-booking-created
spring.cloud.stream.kafka.streams.bindings.bookingConfirmedStream-in-0.consumer.applicationId=stream-analytics-booking-confirmed
spring.cloud.stream.kafka.streams.bindings.bookingFailedStream-in-0.consumer.applicationId=stream-analytics-booking-failed