spring.application.name=booking-service

server.port=8082

spring.datasource.url=jdbc:h2:mem:bookingdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.cloud.stream.bindings.bookingCreated-out-0.destination=booking-created
spring.cloud.stream.bindings.bookingCreated-out-0.content-type=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092

spring.cloud.function.definition=inventoryReserved;inventoryRejected;paymentCompleted;paymentFailed

spring.cloud.stream.bindings.inventoryReserved-in-0.destination=inventory-reserved
spring.cloud.stream.bindings.inventoryReserved-in-0.group=booking-service
spring.cloud.stream.bindings.inventoryReserved-in-0.content-type=application/json

spring.cloud.stream.bindings.inventoryRejected-in-0.destination=inventory-rejected
spring.cloud.stream.bindings.inventoryRejected-in-0.group=booking-service
spring.cloud.stream.bindings.inventoryRejected-in-0.content-type=application/json

spring.cloud.stream.bindings.paymentRequested-out-0.destination=payment-requested
spring.cloud.stream.bindings.paymentRequested-out-0.content-type=application/json

spring.cloud.stream.bindings.paymentCompleted-in-0.destination=payment-completed
spring.cloud.stream.bindings.paymentCompleted-in-0.group=booking-service
spring.cloud.stream.bindings.paymentCompleted-in-0.content-type=application/json

spring.cloud.stream.bindings.paymentFailed-in-0.destination=payment-failed
spring.cloud.stream.bindings.paymentFailed-in-0.group=booking-service
spring.cloud.stream.bindings.paymentFailed-in-0.content-type=application/json

spring.cloud.stream.bindings.bookingConfirmed-out-0.destination=booking-confirmed
spring.cloud.stream.bindings.bookingConfirmed-out-0.content-type=application/json

spring.cloud.stream.bindings.bookingFailed-out-0.destination=booking-failed
spring.cloud.stream.bindings.bookingFailed-out-0.content-type=application/json