spring.application.name=payment-service

server.port=8083

spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.cloud.function.definition=paymentRequested

spring.cloud.stream.bindings.paymentRequested-in-0.destination=payment-requested
spring.cloud.stream.bindings.paymentRequested-in-0.group=payment-service
spring.cloud.stream.bindings.paymentRequested-in-0.content-type=application/json

spring.cloud.stream.bindings.paymentCompleted-out-0.destination=payment-completed
spring.cloud.stream.bindings.paymentCompleted-out-0.content-type=application/json

spring.cloud.stream.bindings.paymentFailed-out-0.destination=payment-failed
spring.cloud.stream.bindings.paymentFailed-out-0.content-type=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092